apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
spec:
  selector:
    matchLabels:
      app: web
  replicas: 4
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: webapp
        image: httpd
        ports:
        - containerPort: 80
